# Anchors for repeated field definitions
# -------------------------------------
anchors:
  fields:
    draft: &field-draft
      label: "Draft"
      name: "draft"
      widget: "boolean"
      default: false
    title: &field-title
      label: "Title"
      name: "title"
      widget: "string"
      required: true
    description: &field-description
      label: "Description"
      name: "description"
      widget: "text" # Use text for potentially longer descriptions
      required: true
    image: &field-image
      label: "Main Image"
      name: "image"
      widget: "image"
      required: true
    body: &field-body
      label: "Body"
      name: "body"
      widget: "markdown"
      required: true
    icon: &field-icon
      label: "Icon"
      name: "icon"
      widget: "string"
      hint: "Enter Iconify Icon Name eg. 'mdi:user'"
      required: true
    url_pattern: &pattern-url
      pattern: ['^https?://.*', "Must be a valid URL starting with http:// or https://"]

local_backend: true

backend:
  name: git-gateway
  branch: main

media_folder: "src/assets/images"
public_folder: "../../assets/images"

site_url: https://hmginternational.com
logo_url: https://hmginternational.com/icon-512.png

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

collections:
  - name: "categories"
    label: "Categories"
    label_singular: "Category"
    folder: "src/content/categories"
    create: true
    fields:
      - *field-draft
      - *field-title
      - *field-description
      - *field-icon
      - *field-image
      - <<: *field-body
        required: false

  - name: "collaborations"
    label: "Collaborations"
    label_singular: "Collaboration"
    folder: "src/content/collaborations"
    create: true
    fields:
      - *field-draft
      - *field-title
      - <<: *field-description
        required: false
      - label: "Publish Date"
        name: "pubDate"
        widget: "datetime"
        required: false
      - <<: *field-image
        required: false
      - *field-body

  - name: "pages"
    label: "Pages"
    label_singular: "Page"
    folder: "src/content/pages"
    create: true
    fields:
      - *field-draft
      - label: "Menu Title"
        name: "menutitle"
        widget: "string"
        hint: "Short title for side menu"
        required: false
      - *field-title
      - <<: *field-description
        required: false
      - label: "Publish Date"
        name: "pubDate"
        widget: "datetime"
        required: false
      - <<: *field-image
        required: false
      - <<: *field-icon
        required: false
      - label: "Sort Order"
        name: "order"
        widget: "number"
        value_type: "int"
        hint: "Enter sequence that pages should be displayed in a menu"
        required: false
      - *field-body

  - name: "partner"
    label: "Partners"
    label_singular: "Partner"
    folder: "src/content/partner"
    create: true
    fields:
      - *field-draft
      - *field-title
      - *field-description
      - label: "Link"
        name: "link"
        widget: "string"
        required: false
        <<: *pattern-url
      - *field-image
      - label: "Additional Images"
        name: "images"
        widget: "list"
        # Using a simple field without 'name' ensures a list of strings
        field: { name: "image", label: "Image", widget: "image" }
        required: false
      - label: "Categories"
        name: "categories"
        widget: "relation"
        collection: "categories"
        value_field: "{{slug}}"
        search_fields: ["title"]
        display_fields: ["title"]
        multiple: true
        min: 1
        filters:
          - field: "draft"
            values: [false]
      - label: "Cuisine"
        name: "cuisine"
        widget: "list"
        # list widget with no 'field' or 'fields' defaults to list of strings
        required: false
      - label: "Country/State"
        name: "region"
        widget: "relation"
        collection: "region"
        value_field: "{{slug}}"
        search_fields: ["title"]
        display_fields: ["title"]
        multiple: false
        filters:
          - field: "draft"
            values: [false]
        hint: "Select country of state partner is in."
        required: true
      - label: "Address"
        name: "address"
        widget: "text" # Better for potential long addresses
        required: false
      - label: "Discount %"
        name: "discount_pct"
        widget: "number"
        value_type: "int"
        default: 0
        required: false
      - label: "Discount Text"
        name: "discount_text"
        widget: "text"
        required: false
      - label: "Comment"
        name: "comment"
        widget: "text"
        required: false
      - label: "Coordinates"
        name: "coordinates"
        widget: "object"
        required: false
        fields:
          - label: "Latitude"
            name: "lat"
            widget: "number"
            value_type: "float"
            required: true
          - label: "Longitude"
            name: "lng"
            widget: "number"
            value_type: "float"
            required: true
      - *field-body

  - name: "region"
    label: "Countries/States"
    label_singular: "Country/State"
    folder: "src/content/region"
    create: true
    fields:
      - *field-draft
      - *field-title
      - <<: *field-description
        required: false
      - label: "Country"
        name: "country"
        widget: "relation"
        collection: "region"
        value_field: "{{slug}}"
        search_fields: ["title"]
        display_fields: ["title"]
        multiple: false
        required: false
        filters:
          - field: "draft"
            values: [false]
          - field: "country"
            values: ["international"]
        hint: "Select 'international' if this is a country. If this is a region or state within a country, then select the country this belongs in."
      - *field-icon
      - *field-image
      - <<: *field-body
        required: false
